---
- hosts: kubernetes
  gather_facts: False
  tasks:
    - name: create docker folder
      file: 
        path: "/etc/docker"
        state: directory
    
    - name: copy daemon.json
      copy: src=docker/daemon.json dest=/etc/docker force=yes backup=yes