---
- hosts: kubernetes
  gather_facts: False
  tasks:
    - name: stop firewalld
      service: 
        name: firewalld 
        state: stopped
        
    - name: disable firewalld
      service: 
        name: firewalld 
        enabled: no
