---
- hosts: all
  tasks:
    - name: set repo hosts
      command: echo {{item.ansible_ssh_host}}  "repo.io" >> /etc/hosts
      with_items: "{{ groups['repo'] }}"
      
    - name: set harbor hosts
      command: echo {{item.ansible_ssh_host}}  "avic.io" >> /etc/hosts
      with_items: "{{ groups['harbor'] }}"
