---
- hosts: harbor:kubernetes
  tasks:
  	- name: delete repo hosts
      shell: sed /repo.io/d  /etc/hosts
      
    - name: delete harbor hosts
      shell: sed /avic.io/d  /etc/hosts
  
    - name: set repo hosts
      shell: echo "{{hostvars[item].ansible_ssh_host}}"  "repo.io" >> /etc/hosts
      with_items: "{{ groups['repo'] }}"
      
    - name: set harbor hosts
      shell: echo {{item.ansible_ssh_host}}  "avic.io" >> /etc/hosts
      with_items: "{{ groups['harbor'] }}"
