---
- hosts: harbor:kubernetes
  tasks:
    - name: del hosts
      lineinfile: dest=/etc/hosts state=absent regexp="(?=avic.io)"
  
    - name: set hosts
      shell: echo "{{hostvars[item].ansible_ssh_host}}"  "avic.io" >> /etc/hosts
      with_items: "{{ groups['harbor'] }}"