---
- hosts: harbor:kubernetes
  tasks:
    - name: del hosts
      shell: sed /avic.io/d  /etc/hosts
  
    - name: set hosts
      shell: echo "{{hostvars[item].ansible_ssh_host}}"  "avic.io" >> /etc/hosts
      with_items: "{{ groups['harbor'] }}"