---
- hosts: kubernetes
  tasks:
    - name: stop networkmanager
      service: 
        name: NetworkManager 
        state: stopped
    - name: disable networkmanager
      service: 
        name: NetworkManager 
        enabled: no
